### ISSUE TITLE
Unable to build on Solaris 11.4/amd64

### ISSUE THREAD

**Issue by andrewhotlab** [fastfetch-cli/fastfetch#2173]
### Read the FAQ first

- [x] I have checked the FAQ but the issue is not covered

### Description

Here is the stage where the build process hangs. I have no clue about the cause.
```
[ 25%] Building C object CMakeFiles/libfastfetch.dir/src/detection/zpool/zpool.c.o
/root/fastfetch/src/detection/zpool/zpool.c: In function ‘enumZpoolCallback’  :
/root/fastfetch/src/detection/zpool/zpool.c:54:9: error: too many arguments to function ‘data->ffzpool_get_prop’
   54 |     if (data->ffzpool_get_prop(zpool, data->props.name, buf, ARRAY_SIZE(buf), &source, false) == 0)
      |         ^~~~
/root/fastfetch/src/detection/zpool/zpool.c:58:9: error: too many arguments to function ‘data->ffzpool_get_prop’
   58 |     if (data->ffzpool_get_prop(zpool, data->props.health, buf, ARRAY_SIZE(buf), &source, false) == 0)
      |         ^~~~
gmake[3]: *** [CMakeFiles/libfastfetch.dir/build.make:818: CMakeFiles/libfastfetch.dir/src/detection/zpool/zpool.c.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:87: CMakeFiles/libfastfetch.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:120: CMakeFiles/fastfetch.dir/rule] Error 2
gmake: *** [Makefile:203: fastfetch] Error 2
```

### Version used

master and 2.58.0

### Bug prevalence

Always

### Regression

Yes

### Installation

Built from source

### Configuration

```jsonc

```

### System information

```jsonc
Oracle Solaris 11.4
```

### Features built-in

```text
unable to catch
```

**Comment by Verdgil** [comment]
I also have this bug but in Sparc64

**Comment by CarterLi** [comment]
It's not a bug. Fastfetch currently supports illumos (a.k.a the modern OpenSolaris) only, but it doesn't support Solaris.

> Currently, it supports Linux, macOS, Windows 7+, Android, FreeBSD, OpenBSD, NetBSD, DragonFly, Haiku, and illumos (SunOS).


Solaris is not illumos.

**Comment by andrewhotlab** [comment]
Well, so it’s the expected behavior. Thanks.

**Comment by Verdgil** [comment]
@andrewhotlab let's try build now

**Comment by andrewhotlab** [comment]
Thank you very much @Verdgil , now the build goes on, then stops at this other point:
```
[ 87%] Building C object CMakeFiles/libfastfetch.dir/src/detection/media/media_linux.c.o
/root/fastfetch/src/detection/media/media_linux.c: In function ‘getBusProperties’:
/root/fastfetch/src/detection/media/media_linux.c:156:36: error: implicit declaration of function ‘memrchr’; did you mean ‘memchr’? [-Wimplicit-function-declaration]
  156 |             const char* fileName = memrchr(result->url.chars, '/', result->url.length);
      |                                    ^~~~~~~
      |                                    memchr
/root/fastfetch/src/detection/media/media_linux.c:156:36: error: initialization of ‘const char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
gmake[3]: *** [CMakeFiles/libfastfetch.dir/build.make:2736: CMakeFiles/libfastfetch.dir/src/detection/media/media_linux.c.o] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:87: CMakeFiles/libfastfetch.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:120: CMakeFiles/fastfetch.dir/rule] Error 2
gmake: *** [Makefile:203: fastfetch] Error 2
```

**Comment by andrewhotlab** [comment]
Sorry, I'm completely clueless on this matter, but it looks like changing the item "memrchr" to "memchr" in `src/detection/media/media_linux.c` fixed the problem:

![Image](https://github.com/user-attachments/assets/c6689dae-c4a2-42c3-93aa-2b14e56ffb56)

Thank you very much for your help!!
