### ISSUE TITLE
Missing support for ddcutil 2.0.0 (1.4.1 works)

### ISSUE THREAD

**Issue by JamiKettunen** [fastfetch-cli/fastfetch#576]
With [ddcutil `v2.0.0`](https://github.com/rockowitz/ddcutil/releases/tag/v2.0.0) when I run the following:
```sh
env NO_CONFIG=1 fastfetch --load-config all --show-errors --stat --multithreading false --disable-linewrap false --hide-cursor false
```
I only get `Brightness: No result is detected.` while installing [ddcutil `v1.4.1`](https://github.com/rockowitz/ddcutil/releases/tag/v1.4.1) makes `Brightness (HPN): 89%` and `Brightness (VSC): 60%`  appear as expected.

Fwiw I was testing this on [Chimera Linux](https://chimera-linux.org/) with my packaging looking like https://github.com/chimera-linux/cports/compare/master...JamiKettunen:cports:fastfetch

Let me know if you need any other details or if this is reproducible under another distribution with an updated `ddcutil` version :)

**Comment by CarterLi** [comment]
Please make sure that `ddcutil getvcp 10` works first, and try fastfetch again.

If it still doesn't work, there must be some imcompatibility between 1.4 and 2.0. [The code](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/brightness/brightness_linux.c#L105) is very simple and you may debug it. If you can't, I'll try debug it myself after Fedora upgrades ddcutil to 2.0.

**Comment by JamiKettunen** [comment]
Sorry for the long delay, that seems to have done the trick. I suppose it should try both sonames since for `fastfetch` purposes both seem to be "compatible"? I suppose it'll crash when that's not the case but could be somehow dealt with as well if it comes up

**Comment by CarterLi** [comment]
FF_LIBRARY_LOAD will [try lower versions if the specified version is not found](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/common/library.c#L39).

**Comment by Bo98** [comment]
Looks like it broke again in e9c2a43de1f3951daa38b3c53da793747c379d1d:

```
  In file included from /tmp/fastfetch-20231014-20832-1ne6cfg/fastfetch-2.1.1/src/detection/brightness/brightness_linux.c:90:
  /tmp/fastfetch-20231014-20832-1ne6cfg/fastfetch-2.1.1/src/detection/brightness/brightness_linux.c: In function ‘detectWithDdcci’:
  /tmp/fastfetch-20231014-20832-1ne6cfg/fastfetch-2.1.1/src/detection/brightness/brightness_linux.c:103:48: error: ‘ddca_set_default_sleep_multiplier’ undeclared (first use in this function); did you mean ‘ddca_set_sleep_multiplier’?
    103 |     FF_LIBRARY_LOAD_SYMBOL_MESSAGE(libddcutil, ddca_set_default_sleep_multiplier)
        |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

From ddcutil release notes:

> With the ability to configure libddcutil operation both by the ddcutil 
configuration file and by passing an option string in the ddca_init() arguments, 
several API functions are no longer needed and have been removed:
>
> [...]
> - ddca_set_default_sleep_multiplier(), ddca_set_global_sleep_multiplier()
>
> [...]
