### ISSUE TITLE
[BUG] Building tests uses vendored yyjson

### ISSUE THREAD

**Issue by Dariqq** [fastfetch-cli/fastfetch#1244]
# General description of bug:

* What happened:

Building with "-DBUILD_TESTS=ON" and "-DENABLE_SYSTEM_YYJSON=YES" fails when the vendored yyjson is not present:

```
[100%] Building C object CMakeFiles/fastfetch-test-format.dir/tests/format.c.o
/gnu/store/86fc8bi3mciljxz7c79jx8zr4wsx7xw8-gcc-11.4.0/bin/gcc -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_XOPEN_SOURCE -D__STDC_WANT_LIB_EXT1__=1 -I/tmp/guix-build-fastfetch-2.23.0.drv-0/build -I/tmp/guix-build-fastfetch-2.23.0.drv-0/source/src -Wall -Wextra -Wconversion -Werror=uninitialized -Werror=return-type -Werror=incompatible-pointer-types -Werror=implicit-function-declaration -Werror=int-conversion -O2 -g -DNDEBUG -flto=auto -fno-fat-lto-objects -std=gnu11 -MD -MT CMakeFiles/fastfetch-test-format.dir/tests/format.c.o -MF CMakeFiles/fastfetch-test-format.dir/tests/format.c.o.d -o CMakeFiles/fastfetch-test-format.dir/tests/format.c.o -c /tmp/guix-build-fastfetch-2.23.0.drv-0/source/tests/format.c
In file included from /tmp/guix-build-fastfetch-2.23.0.drv-0/source/tests/format.c:3:
/tmp/guix-build-fastfetch-2.23.0.drv-0/source/src/fastfetch.h:14:14: fatal error: 3rdparty/yyjson/yyjson.h: No such file or directory
   14 |     #include "3rdparty/yyjson/yyjson.h"
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I have bisected this to 85d89395a94322914337b8e3a1012f4edb740b8a.

* What should happen: Use the system provided yyjson.
* Fastfetch version used: 2.23.0
* Did it work in an older version: Yes, 2.22.0 and before
